---
# We pull in the admin username and keyfile from environment.yml
- hosts: all
  sudo: True
  tasks:
    - include: tasks/sudoers.yml
    - include: tasks/user.yml user={{ admin_username }} keypath={{ admin_key_path }} group="wheel"
    - include: tasks/yum.yml
