---
# File: setup.yml
# Part: nodejs
#
# Description: Installs nodejs from source
#
# Parameters - Must be definied in playbook:
#   - node_path = The nodejs path
#   - node_prefix = The prefix
#   - node_tarball = The tarball filename at nodejs.org
#   - node_version = The wanted version of node to be installed

- name: Node.js | Get version of node.js if installed
  shell: "{{ node_path }}/bin/node -v |  sed 's/v//'"
  register: installed
  ignore_errors: True

- name: Node.js | Fetching node.js source
  action: get_url url=http://nodejs.org/dist/v{{ node_version }}/{{ node_tarball }} dest=/tmp/
  when: installed.stdout != node_version

- name: Node.js | Unpack node.js tarball
  command: tar zxf {{ node_tarball }} chdir=/tmp
  when: installed.stdout != node_version

- name: Node.js | Configure
  shell: /usr/bin/python ./configure --prefix={{ node_path }} chdir=/tmp/{{ node_prefix }}
  when: installed.stdout != node_version

- name: Node.js | Make
  shell: /usr/bin/make chdir=/tmp/{{ node_prefix }}/
  when: installed.stdout != node_version

- name: Node.js | Make install
  shell: /usr/bin/make install chdir=/tmp/{{ node_prefix }}/
  when: installed.stdout != node_version
